name: Bug report
description: Report a problem with AzureAutoHibernate
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What happened? What did you expect to happen?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `AzureAutoHibernate.exe -version` (or Git tag / commit)

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Step-by-step instructions so we can reproduce the issue
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Windows version, Azure environment, VM size, etc.

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Event Viewer entries, console output, config snippets, etc.
