name: Feature request
description: Suggest an idea or improvement for AzureAutoHibernate
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like AzureAutoHibernate to work?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Have you considered any alternative solutions or workarounds?

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Any other context, mockups, or details you'd like to add
